language: cpp
os:
 - linux
 - osx

# When updating be sure to add a section
# to the matrix to cover the distro
dist: bionic

compiler:
    - gcc
    - clang

jobs:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          name: "Ubuntu 14.04 LTS - GCC"
        - os: linux
          dist: trusty
          compiler: clang
          name: "Ubuntu 14.04 LTS - Clang"
        - os: linux
          dist: xenial
          compiler: gcc
          name: "Ubuntu 16.04 LTS - GCC"
        - os: linux
          dist: xenial
          compiler: clang
          name: "Ubuntu 16.04 LTS - Clang"
        - os: osx
          osx_image: xcode11.3
    allow_failures:
        - compiler: clang
        - os: osx
    fast_finish: true

addons:
  apt:
    packages:
      - python-dev
      - libgl1-mesa-glx
      - freeglut3-dev
      - libopenal-dev
      - libsdl-gfx1.2-dev
      - libvorbis-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk2.0-dev
      - libboost-python-dev
  homebrew:
     update: true
     packages:
      - mesa
      - openal-soft
      - sdl
      - libvorbis
      - jpeg
      - libpng
      - gtk+
      - gtkglext
      - boost-python

script:
  - ./sh/vsbuild.sh
